export const vehiclesTypes: string[] = [
   'Compacto',
   'Sedan',
   'SUV',
   'Coupé',
   'Musculoso',
   'Clássico Esportivo',
   'Esportivo',
   'Super',
   'Moto',
   'Off-Road',
   'Industrial',
   'Utilitário',
   'Van',
   'Ciclo',
   'Barco',
   'Helicóptero',
   'Avião',
   'Serviço',
   'Emergência',
   'Militar',
   'Comercial',
   'Trem',
   'Aberto',
];
